discord_token: ""
discord_guild: ""
discord_bot_channel: 

bot_symbol: $
color: 0x408080

default_task:
    - users: 0
    - description: "This is the default task."
    - estimated_time: 120
    - real_time: 200
    - tags: []
